import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";
import Footer from "./components/Footer";
import Header from "./components/Header";

const montserratBlack = localFont({
  src: [
    {
      path: './fonts/Montserrat-Black.ttf',
      weight: '600',
      style: 'normal',
    },
  ],
  variable: '--font-montserrat-black',
  display: 'swap',
})

const montserratBold = localFont({
  src: [
    {
      path: './fonts/Montserrat-Bold.ttf',
      weight: '600',
      style: 'normal',
    },
  ],
  variable: '--font-montserrat-bold',
  display: 'swap',
})

const montserratBoldItalic = localFont({
  src: [
    {
      path: './fonts/Montserrat-BoldItalic.ttf',
      weight: '600',
      style: 'italic',
    },
  ],
  variable: '--font-montserrat-bold-italic',
  display: 'swap',
})

const montserratLightItalic = localFont({
  src: [
    {
      path: './fonts/Montserrat-LightItalic.ttf',
      weight: '300',
      style: 'italic',
    },
  ],
  variable: '--font-montserrat-light-italic',
  display: 'swap',
})

const montserratRegular = localFont({
  src: [
    {
      path: './fonts/Montserrat-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-montserrat-regular',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "A&D Empire Group",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserratBlack.variable} ${montserratBold.variable} ${montserratBoldItalic.variable} ${montserratLightItalic.variable} ${montserratRegular.variable} antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
